export { defaut as Article } from './article/Article'
export { defaut as Brand } from './Brand/Brand'
export { defaut as CTA } from './CTA/CTA'
export { defaut as Feature } from './Feature/Feature'
export { defaut as Navbar } from './Navbar/Navbar'